/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Kaijus } from "./Kaijus";
export type { Mutants } from "./Mutants";
export type { Rwaste } from "./Rwaste";

export { Kaijus__factory } from "./factories/Kaijus__factory";
export { Mutants__factory } from "./factories/Mutants__factory";
export { Rwaste__factory } from "./factories/Rwaste__factory";
